### ISSUE TITLE
Botão de Próxima Seção

### ISSUE THREAD

**Issue by Novout** [jpaulohe4rt/markdown4noobs#2]
Nas seções, além do botão de `Voltar para o inicio` poderia ter na direita `Próxima Seção` para facilitar a leitura.

**Comment by danielhe4rt** [comment]
Concordo com o @Novout e isso possivelmente será padronizado em todos os repositórios.

**Comment by gusutabo** [comment]
Irei fazer a adição agora, Muito obrigado pela sugestão!
